"""esquema inicial: integraciones, credenciales, comisiones, transacciones, webhooks

Revision ID: 80645fa64515
Revises: 
Create Date: 2026-08-06 04:26:52.305646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import nexolu_payments_core.core.security.crypto


# revision identifiers, used by Alembic.
revision: str = '80645fa64515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('webhook_secret', nexolu_payments_core.core.security.crypto.EncryptedString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('fee_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('integration_id', sa.String(length=32), nullable=False),
    sa.Column('provider_slug', sa.String(length=32), nullable=False),
    sa.Column('percent_fee', sa.Float(), nullable=False),
    sa.Column('fixed_fee_cop', sa.Integer(), nullable=False),
    sa.Column('iva_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fee_schedules_integration', 'fee_schedules', ['integration_id', 'provider_slug', 'is_active'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('integration_id', sa.String(length=32), nullable=False),
    sa.Column('provider_slug', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('private_key', nexolu_payments_core.core.security.crypto.EncryptedString(length=255), nullable=False),
    sa.Column('integrity_secret', nexolu_payments_core.core.security.crypto.EncryptedString(length=255), nullable=False),
    sa.Column('events_secret', nexolu_payments_core.core.security.crypto.EncryptedString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'provider_slug', 'environment', name='uq_credential_integration_provider_env')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('integration_id', sa.String(length=32), nullable=False),
    sa.Column('provider_slug', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('amount_cop', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fee_cop', sa.Integer(), nullable=True),
    sa.Column('net_amount_cop', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'reference', name='uq_transaction_reference_per_integration')
    )
    op.create_index('ix_transactions_integration_status', 'transactions', ['integration_id', 'status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('integration_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_transaction', 'webhook_deliveries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_deliveries_transaction', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_transactions_integration_status', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('provider_credentials')
    op.drop_index('ix_fee_schedules_integration', table_name='fee_schedules')
    op.drop_table('fee_schedules')
    op.drop_table('integrations')
    # ### end Alembic commands ###
